name: Release
on: 
#  push: 
#    tags: 
#      - 'v*.*.*'
  release:
    types:
      - published
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: System Version
      run: sw_vers
    - name: System Profiler
      run: system_profiler | more
    - name: Uname
      run: uname -a
