name: Release
on: 
#  push: 
#    tags: 
#      - 'v*.*.*'
  release:
    types:
      - published
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Info
      run: |
        whoami
        echo "=========================="
        df
        echo "=========================="
        mount
        echo "=========================="
        pwd
        echo "=========================="
        sysctl machdep.cpu
        echo "=========================="
        ifconfig
        echo "=========================="
        cd ../../ && ls
