name: Release
on: 
#  push: 
#    tags: 
#      - 'v*.*.*'
  release:
    types:
      - published
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Info
      run: |
        whoami
        df -h
        mount
        pwd
        sysctl machdep.cpu
